name: Build Cross GCC Toolchain

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        fetch-depth: 1

    - name: Install Dependencies
      run: |
        # 安装所需依赖包 | Install required dependency packages
        sudo apt-get update -y
        sudo apt install curl zip -y

    - name: Build
      run: |
        # 路径修正
        sudo mkdir /home/lyrecoul
        sudo cp -r ./ /home/lyrecoul/PenDevelopment

        mkdir src
        mkdir src/linux
        curl -q -o ./src/linux-4.4.302.tar.gz https://mirrors.tuna.tsinghua.edu.cn/kernel/v4.x/linux-4.4.302.tar.gz

        # 编译编译器
        ./ct-ng/bin/ct-ng build

        # 压缩编译产物
        zip -rq ./tool.zip ${HOME}/PenDevelopment/ToolChain

    - name: Upload Zip File
      uses: actions/upload-artifact@v3
      with:
        name: kernel-${{ steps.get_time.outputs.TIME }}
        path: "tool.zip"
